
package com.digitaldynamics.pms.service;

import org.springframework.mail.SimpleMailMessage;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.stereotype.Service;

@Service
public class EmailService {

    private final JavaMailSender mailSender;

    public EmailService(JavaMailSender mailSender) {
        this.mailSender = mailSender;
    }

    private void send(String to, String subject, String body) {

        SimpleMailMessage message = new SimpleMailMessage();

        message.setTo(to);
        message.setSubject(subject);
        message.setText(body);

        mailSender.send(message);
    }

    public void sendRequisitionSubmitted(
            String managerEmail,
            String requisitionNumber,
            String requesterName) {

        send(
                managerEmail,
                "New Requisition Awaiting Approval",
                "Dear Procurement Manager,\n\n" +
                "A new requisition has been submitted.\n\n" +
                "Requisition Number: " + requisitionNumber + "\n" +
                "Requested By: " + requesterName + "\n\n" +
                "Please review and approve the requisition.\n\n" +
                "Regards,\nProcurement Management System"
        );
    }

    public void sendRequisitionApproved(
            String requesterEmail,
            String requisitionNumber) {

        send(
                requesterEmail,
                "Requisition Approved",
                "Dear User,\n\n" +
                "Your requisition " + requisitionNumber +
                " has been approved.\n\n" +
                "Regards,\nProcurement Management System"
        );
    }

    public void sendRequisitionRejected(
            String requesterEmail,
            String requisitionNumber,
            String reason) {

        send(
                requesterEmail,
                "Requisition Rejected",
                "Dear User,\n\n" +
                "Your requisition " + requisitionNumber +
                " has been rejected.\n\n" +
                "Reason: " + reason +
                "\n\nRegards,\nProcurement Management System"
        );
    }

    public void sendRfqInvitation(
            String supplierEmail,
            String rfqNumber) {

        send(
                supplierEmail,
                "Request For Quotation (RFQ)",
                "Dear Supplier,\n\n" +
                "You are invited to submit a quotation.\n\n" +
                "RFQ Number: " + rfqNumber +
                "\n\nRegards,\nProcurement Management System"
        );
    }

    public void sendQuotationReceived(
            String procurementEmail,
            String supplierName,
            String rfqNumber) {

        send(
                procurementEmail,
                "Quotation Received",
                "A quotation has been received.\n\n" +
                "Supplier: " + supplierName + "\n" +
                "RFQ Number: " + rfqNumber +
                "\n\nRegards,\nProcurement Management System"
        );
    }

    public void sendUserRegistration(
            String userEmail,
            String fullName) {

        send(
                userEmail,
                "Welcome to Procurement Management System",
                "Dear " + fullName + ",\n\n" +
                "Your account has been created successfully.\n\n" +
                "Regards,\nProcurement Management System"
        );
    }

    public void sendPasswordReset(
            String userEmail,
            String resetLink) {

        send(
                userEmail,
                "Password Reset Request",
                "Click the link below to reset your password:\n\n"
                        + resetLink
        );
    }

    

public void sendSystemTestEmail(String recipientEmail) {

    send(
            recipientEmail,
            "Procurement Management System - Email Service Verification",
            "Dear Team,\n\n" +
            "This email confirms that the Procurement Management System (PMS) " +
            "email notification service has been successfully configured and tested.\n\n" +
            "System Information:\n" +
            "- Application: Procurement Management System\n" +
            "- Email Service: Gmail SMTP\n" +
            "- Security: TLS (Port 587)\n" +
            "- Status: Operational\n\n" +
            "Test Details:\n" +
            "- Purpose: SMTP Configuration Verification\n" +
            "- Result: Successful\n\n" +
            "This is an automated email generated by the Procurement Management System.\n" +
            "No action is required.\n\n" +
            "Regards,\n" +
            "Digital Dynamics\n" +
            "Procurement Management System"
    );
}


}
